import json
import fire
from .select_checkers import issue_codes


def format_output(findings_path: str) -> str:
    # Load findings JSON file generated by DynaPyt
    with open(findings_path, "r") as f:
        findings = json.load(f)
    
    # Use set to deduplicate findings across all analyses
    res = set()
    
    # Iterate through findings from each analysis
    for finding in findings:
        # Skip findings with no results
        if len(finding["results"]) > 0:
            # Process each checker's findings
            for _, checker_finding in finding["results"].items():
                if len(checker_finding["results"]) > 0:
                    # Process each issue type (e.g., PC-01, SL-01)
                    for issue_code, issue_list in checker_finding["results"].items():
                        code = ""
                        # Map issue code to standard code (handle aliases)
                        for c, i in issue_codes.items():
                            if issue_code in i["aliases"] or issue_code == c:
                                code = c
                                break
                        # Format each individual issue as: CODE: file:line: message
                        for issue in issue_list:
                            res.add(
                                f"{code}: {issue['finding']['location']['file']}: {issue['finding']['location']['start_line']}: {issue['finding']['msg']}"
                            )
    # Return all unique findings sorted by set order, joined with newlines
    return "\n".join(list(res))


if __name__ == "__main__":
    fire.Fire(format_output)
